version: "3.3"
services:
  db:
    container_name: mysql8
    image: mysql:8.0.21
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: "CYN_AUTHENTICATION_SERVICE"
      # 配置自定义用户名
      MYSQL_USER: "user"
      # 配置自定义用户的密码
      MYSQL_PASSWORD: "password"
      # 配置root用户的密码
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # 配置端口映射
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3307"
    expose:
      # 暴露MYSQL端口
      # Opens port 3306 on the container
      - "3307"
